data:
    name: tomatoes
    data_dir: training
    image_dir: rgb
    depth_dir: depth
    train_size: 50
    val_size: 10
    batch_size: 5
    grayscale: false
    resize : [340,240]
    num_workers: 5
    test: false
model:
    name: initialModel
    input_shape: [3,340,240]
train:
    seed: None
    epochs: 40
    log_every_iter: 1
    eval_every_iter: 1
    loss: ProvidedLossTraining
    optimizer:
        name: sgd  # adam, adamw, rmsprop
        lr: 0.001
        optimizer_options:  # need to be added accordingly to optimizer
            momentum: 0.9
    lr: 5e-5
    lr_schedule:
        start: 20
        type: exp  # factor, exp, None
        on_epoch: true
        exp_div_10: 2

# TODO Selection of cloud or local computing
# TODO include all necessary and remove all unnecessary settings
# TODO include differentiatiation between training and evaluation
